# This provides metadata for NIH-plug's `cargo xtask bundle <foo>` plugin
# bundler. This file's syntax is as follows:
#
# [package_name]
# name = "Human Readable Plugin Name"  # defaults to <package_name>

[diopser]
name = "Diopser"
